### ISSUE TITLE
Create project template?

### ISSUE THREAD

**Issue by ogrotten** [astrochili/defold-vscode-guide#8]
Under the Quickstart, the first step says.

> 1. Download master to use it as the template project.

How is this set as "the template project"?

**Comment by astrochili** [comment]
I agree, it's a little confusing. I don't really know how to add a real template project to Defold. Here we are talking about just copying the repository and taking its files as the basis of your future project.

**Comment by gianmichelemariani** [comment]
At the moment you can't set new template projects in Defold. 
I'm doing something similar for a project of mine, and the way I'm approaching it is through an editor extension with a menu to initialise what I need. I basically create the files on the fly with this. 
Not sure if it works in your case because you also have the debugger and other things, but maybe it's worth a try?

**Comment by astrochili** [comment]
> Not sure if it works in your case because you also have the debugger and other things, but maybe it's worth a try?

True, unfortunately. Installing the extension is not suitable here, because the extension is installed in a separate folder and is stored as a zip archive. Here there is only one lua-file, and the rest are invisible files and folders for VSCode and git.

**Comment by astrochili** [comment]
By the way, I just discovered the templates on github. I think this is a good option!

<img width="888" alt="Screenshot 2022-02-03 at 13 58 44" src="https://user-images.githubusercontent.com/4752473/152330195-4a9e41bb-4441-4c45-9adf-fe3b7ef4fa7d.png">
